name: Build Windows Executable (Folder Mode)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable (folder mode)
      run: |
        pyinstaller main.py

    - name: Upload artifact (entire dist folder)
      uses: actions/upload-artifact@v4
      with:
        name: birthdaygame-folder
        path: dist/main/
